In [1]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2

In [2]:
import librosa
import numpy as np    
import os
import signal
import subprocess
import json
import uuid
from IPython.display import HTML

Extractor (Input Validation, Chunking, Mapping From file_csv and annotations_csv to chunks)

In [3]:
from acoustic_knowledge_discovery import extractors

In [ ]:
extractor = extractors.Extractor(
    "/home/c.zhang.97/mount/gorongosa_recordings_small_test.csv", #file metadata csv
    #"/home/s.kamboj.400/mount/gorongosa_recordings_small_test.csv",
    #"/home/s.kamboj.400/mount/mexico_recordings.csv",
    "/home/c.zhang.97/mount/gorongosa_recordings_anno.csv", #annoations csv
    #"/home/s.kamboj.400/mount/gorongosa_recordings_anno.csv",
    #"/home/s.kamboj.400/mount/mexico_recordings_anno.csv",
    "/home/c.zhang.97/mount/",#input directory with a files subdirectory for audio files & a XC-templates subdirectory for XC templates
    #"/home/s.kamboj.400/mount/",
    #"/home/s.kamboj.400/unzipped-coral/PaolaMexico/",
    chunk_size = 5) #chunk size in seconds
chunkDS = extractor.forward()

Kept  11  files after processing files_csv

Casting the dataset:   0%|          | 0/8 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/8 [00:00<?, ? examples/s]

In [5]:
for row in chunkDS.chunk_ds["train"]:
    print(row)
chunkDS.chunk_ds

{'file_name': 'SERRA_20250503_152505.wav', 'Date': '2025-05-03', 'Time': '15:25:05', 'Duration': '00:00:05', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_152505.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_152505.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_160206.wav', 'Date': '2025-05-03', 'Time': '16:02:06', 'Duration': '00:00:11', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_160206.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_160206.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_160206.wav', 'Date': '2025-05-03', 'Time': '16:02:06', 'Duration': '00:00:11', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_160206.wav', 'chunk_start': 5, 'chunk_id': 'SERRA_20250503_160206.wav_5', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_220842.wav', 'Date': '2025-05-03', 'Time': '22:08:42', 'Duration': '00:00:15', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Night', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_220842.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_220842.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_220842.wav', 'Date': '2025-05-03', 'Time': '22:08:42', 'Duration': '00:00:15', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Night', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_220842.wav', 'chunk_start': 5, 'chunk_id': 'SERRA_20250503_220842.wav_5', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_153828.wav', 'Date': '2025-05-03', 'Time': '15:38:28', 'Duration': '00:00:06', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_153828.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_153828.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_175145.wav', 'Date': '2025-05-03', 'Time': '17:51:45', 'Duration': '00:00:06', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_175145.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_175145.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_174918.wav', 'Date': '2025-05-03', 'Time': '17:49:18', 'Duration': '00:00:05', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_174918.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_174918.wav_0', 'Annotation': [], 'Confidence': []}

DatasetDict({
    train: Dataset({
        features: ['file_name', 'Date', 'Time', 'Duration', 'Season', 'Time of Day', 'Audio Hardware', 'Sound Type', 'Location Name', 'Coordinates', 'Audio Channels', 'Sample Rate', 'Bit Depth', 'SR', 'file_path', 'chunk_start', 'chunk_id', 'Annotation', 'Confidence'],
        num_rows: 8
    })
})

File-level Operations

In [6]:
from acoustic_knowledge_discovery.features.feature_preprocessing_pipeline import FeatureSequential
from acoustic_knowledge_discovery import features

TEMPLATE_MATCHING_THRESHOLD = 0.6

pipeline = FeatureSequential(
    features.TemplateMatching(
        extractor.base_dir / "XC_results", # link to directory with XC templates
        TEMPLATE_MATCHING_THRESHOLD,
        chunk_size=extractor.chunk_size
    ),
)

chunkDS = pipeline.forward(chunkDS)

0 total templates
Filtered down to 0 unique species templates
Total matches found above the threshold of 0.6: 0

In [7]:
#verify properly loaded after feature extraction
for row in chunkDS.chunk_ds["train"]:
    #print(row["Annotation"], row["Confidence"])
    print(row)

{'file_name': 'SERRA_20250503_152505.wav', 'Date': '2025-05-03', 'Time': '15:25:05', 'Duration': '00:00:05', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_152505.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_152505.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_160206.wav', 'Date': '2025-05-03', 'Time': '16:02:06', 'Duration': '00:00:11', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_160206.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_160206.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_160206.wav', 'Date': '2025-05-03', 'Time': '16:02:06', 'Duration': '00:00:11', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_160206.wav', 'chunk_start': 5, 'chunk_id': 'SERRA_20250503_160206.wav_5', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_220842.wav', 'Date': '2025-05-03', 'Time': '22:08:42', 'Duration': '00:00:15', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Night', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_220842.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_220842.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_220842.wav', 'Date': '2025-05-03', 'Time': '22:08:42', 'Duration': '00:00:15', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Night', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_220842.wav', 'chunk_start': 5, 'chunk_id': 'SERRA_20250503_220842.wav_5', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_153828.wav', 'Date': '2025-05-03', 'Time': '15:38:28', 'Duration': '00:00:06', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_153828.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_153828.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_175145.wav', 'Date': '2025-05-03', 'Time': '17:51:45', 'Duration': '00:00:06', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_175145.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_175145.wav_0', 'Annotation': [], 'Confidence': []}
{'file_name': 'SERRA_20250503_174918.wav', 'Date': '2025-05-03', 'Time': '17:49:18', 'Duration': '00:00:05', 'Season': 'Transition Rainy to Dry', 'Time of Day': 'Afternoon', 'Audio Hardware': 'Wildlife Accoustics', 'Sound Type': 'Ultrasonic', 'Location Name': 'Sand Forest', 'Coordinates': '18,961373°S  34,342399°E', 'Audio Channels': 'Mono', 'Sample Rate': '256.0 kHz', 'Bit Depth': '16-bit', 'SR': 256000.0, 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_174918.wav', 'chunk_start': 0, 'chunk_id': 'SERRA_20250503_174918.wav_0', 'Annotation': [], 'Confidence': []}

Chunk-level Operations

In [8]:
#Insert EGCI
from acoustic_knowledge_discovery import features

In [9]:
egci = features.EGCI()
chunkDS= egci(chunkDS, extractor.chunk_size, num_proc=1)

Map:   0%|          | 0/8 [00:00<?, ? examples/s]

In [10]:
FREQUENCY_ACTIVITY_THRESHOLD= 0.5
frequency_bin={
    'Low': (20, 200), 
    'Mid': (200, 2000),
    'High': (2000, 20000),
}

freq= features.Frequency(frequency_bin, FREQUENCY_ACTIVITY_THRESHOLD, extractor.chunk_size)
chunkDS= freq(chunkDS)

Computing Frequency Activity feature...

Map (num_proc=4):   0%|          | 0/8 [00:00<?, ? examples/s]

In [11]:
# # For each chunk, get the loudness
# BIN_DICT = {
#     "Low":    (-80.0, -40.0),
#     "Medium": (-40.0, -25.0),
#     "High":   (-25.0, 10.0),
#     "Other" : (10.0, 3000.0)
# }

# vol_feature = features.Volume(BIN_DICT=BIN_DICT, chunk_size= extractor.chunk_size)
# chunkDS= vol_feature(chunkDS)

In [12]:
# from acoustic_knowledge_discovery.features import ACI

# BIN_DICT = {
#     "Low": (0.0, 0.5),
#     "Medium": (0.5, 2.0),
#     "High": (2.0, 10.0),
# }

# activity_feature = features.Activity(BIN_DICT=BIN_DICT, chunk_size=extractor.chunk_size,)
# chunkDS = activity_feature(chunkDS)

In [13]:
# # verify EGCI column properly added
# for row in chunkDS.chunk_ds["train"]:
#     print(row)
chunkDS.chunk_ds

DatasetDict({
    train: Dataset({
        features: ['file_name', 'Date', 'Time', 'Duration', 'Season', 'Time of Day', 'Audio Hardware', 'Sound Type', 'Location Name', 'Coordinates', 'Audio Channels', 'Sample Rate', 'Bit Depth', 'SR', 'file_path', 'chunk_start', 'chunk_id', 'Annotation', 'Confidence', 'EGCI', 'Frequency'],
        num_rows: 8
    })
})

Binning!

In [14]:
from acoustic_knowledge_discovery.postprocessing import MakeBins2dFloat
makebins = MakeBins2dFloat(chunkDS)
egci_bin={
    "low": ( (0.0, 34), (0.0,0.34) ), 
    "medium": ((0.34,0.67),(0.34,0.67)), 
    "high": ((0.67,1),(0.67,1))
}

chunkDS = makebins("EGCI", egci_bin)

Casting the dataset:   0%|          | 0/8 [00:00<?, ? examples/s]

Map:   0%|          | 0/8 [00:00<?, ? examples/s]

In [15]:
# for row in chunkDS.chunk_ds["train"]:
    #label_str = chunkDS.chunk_ds["train"].features["EGCI"].int2str(row["EGCI"])
    # print(row["chunk_id"], row['Volume_dB'], row['Volume_bin'])
chunkDS.chunk_ds

DatasetDict({
    train: Dataset({
        features: ['file_name', 'Date', 'Time', 'Duration', 'Season', 'Time of Day', 'Audio Hardware', 'Sound Type', 'Location Name', 'Coordinates', 'Audio Channels', 'Sample Rate', 'Bit Depth', 'SR', 'file_path', 'chunk_start', 'chunk_id', 'Annotation', 'Confidence', 'Frequency', 'EGCI'],
        num_rows: 8
    })
})

In [16]:
chunkDS.chunk_ds["train"][0]

{'file_name': 'SERRA_20250503_152505.wav',
 'Date': '2025-05-03',
 'Time': '15:25:05',
 'Duration': '00:00:05',
 'Season': 'Transition Rainy to Dry',
 'Time of Day': 'Afternoon',
 'Audio Hardware': 'Wildlife Accoustics',
 'Sound Type': 'Ultrasonic',
 'Location Name': 'Sand Forest',
 'Coordinates': '18,961373°S  34,342399°E',
 'Audio Channels': 'Mono',
 'Sample Rate': '256.0 kHz',
 'Bit Depth': '16-bit',
 'SR': 256000.0,
 'file_path': '/home/c.zhang.97/mount/files/Field trip 1 - Old/Location A (Sand Forrest)/LA_Sand_Forrest_ULTRASONIC_03-05-25/SERRA_20250503_152505.wav',
 'chunk_start': 0,
 'chunk_id': 'SERRA_20250503_152505.wav_0',
 'Annotation': [],
 'Confidence': [],
 'Frequency': ['frequency_Low'],
 'EGCI': 'medium'}

In [17]:
# # Tests that MakeBins1dFloat does work, but it does not make sense to use it on this dataset
# from acoustic_knowledge_discovery.postprocessing import MakeBins1dFloat
# makebins1d = MakeBins1dFloat(chunkDS)
# OneDBin={
#     "low": (0, 5) , 
#     "medium": (5, 10), 
#     "high": (10, 15)
# }

# chunkDS = makebins1d("chunk_start", OneDBin)

# for row in chunkDS.chunk_ds["train"]:
#     print(row["chunk_id"], row["chunk_start"])
# chunkDS.chunk_ds

# AutoEncoder and Clustering

In [18]:
from acoustic_knowledge_discovery.features import AutoEncoderProcessor

autoEncoder = AutoEncoderProcessor(model_path = "sample_models/dim_10_muha.pt", num_dims=10)
chunkDS = autoEncoder(chunkDS, extractor.chunk_size)
chunkDS.chunk_ds

Map:   0%|          | 0/8 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['file_name', 'Date', 'Time', 'Duration', 'Season', 'Time of Day', 'Audio Hardware', 'Sound Type', 'Location Name', 'Coordinates', 'Audio Channels', 'Sample Rate', 'Bit Depth', 'SR', 'file_path', 'chunk_start', 'chunk_id', 'Annotation', 'Confidence', 'Frequency', 'EGCI', 'sample_models/dim_10_muha.pt_embeddings'],
        num_rows: 8
    })
})

In [19]:
from acoustic_knowledge_discovery.postprocessing import Cluster_API

#HEY HEY HEY: You should note that more num_clusters means more possible nodes
# num_clusters should be some number that is less than your dataset
clustering_pipe = Cluster_API(chunkDS, num_clusters=2)
chunkDS = clustering_pipe("sample_models/dim_10_muha.pt_embeddings")
chunkDS.chunk_ds

DatasetDict({
    train: Dataset({
        features: ['file_name', 'Date', 'Time', 'Duration', 'Season', 'Time of Day', 'Audio Hardware', 'Sound Type', 'Location Name', 'Coordinates', 'Audio Channels', 'Sample Rate', 'Bit Depth', 'SR', 'file_path', 'chunk_start', 'chunk_id', 'Annotation', 'Confidence', 'Frequency', 'EGCI', 'sample_models/dim_10_muha.pt_embeddings', 'sample_models/dim_10_muha.pt_embeddings_clusters'],
        num_rows: 8
    })
})

# Convert System to a graph representation

In [20]:
def normalize(v):
    if isinstance(v, list):
        return v
    if isinstance(v, np.ndarray):   # convert numpy array to list
        return v.tolist()
    return [v]  # if it is scalar, then make it list

In [21]:
#test = chunkDS.chunk_ds.select_columns(["file_name", " time_of_day", "season", "species", "chunk_id", "Annotation", "EGCI", "sample_models/dim_10_muha.pt_embeddings_clusters"])
#TODO : change the column names to match dataset
test = chunkDS.chunk_ds.select_columns(["file_name", "Season","Time of Day", "chunk_id", "EGCI", "sample_models/dim_10_muha.pt_embeddings_clusters", "Annotation", "Frequency"])
nodes = test["train"].to_pandas().melt()
nodes = nodes.assign(value=nodes["value"].apply(normalize)).explode("value", ignore_index=True) #necessary so list values are separated
nodes["id"] = nodes["variable"] + "_" + nodes["value"].apply(str)
nodes["group"] = nodes["variable"].apply(lambda x: list(nodes["variable"].unique()).index(x))
nodes[["id", "group"]].head()

                                    id  group
0  file_name_SERRA_20250503_152505.wav      0
1  file_name_SERRA_20250503_160206.wav      0
2  file_name_SERRA_20250503_160206.wav      0
3  file_name_SERRA_20250503_220842.wav      0
4  file_name_SERRA_20250503_220842.wav      0

In [22]:
#connect to file name rather than chunk name
# edge_list = test["train"].to_pandas().melt(id_vars="file_name")
# edge_list = edge_list.assign(value=edge_list["value"].apply(normalize)).explode("value", ignore_index=True)
# edge_list = edge_list.dropna(subset=["value"])# drop Nan
# edge_list["target"] = edge_list["variable"] + "_" + edge_list["value"].apply(str)
# edge_list["source"] = "file_name" + "_" + edge_list["file_name"]
# edge_list["value"] = 1

edge_list = test["train"].to_pandas().melt(id_vars=["chunk_id"])
edge_list = edge_list.assign(value=edge_list["value"].apply(normalize)).explode("value", ignore_index=True)
edge_list = edge_list.dropna(subset=["value"])# drop Nan
edge_list["target"] = edge_list["variable"] + "_" + edge_list["value"].astype(str)
edge_list["source"] = "chunk_id" + "_" + edge_list["chunk_id"]
edge_list["value"] = 1
edge_list[["source", "target", "value"]].head()

,source,target,value
0,chunk_id_SERRA_20250503_152505.wav_0,file_name_SERRA_20250503_152505.wav,1
1,chunk_id_SERRA_20250503_160206.wav_0,file_name_SERRA_20250503_160206.wav,1
2,chunk_id_SERRA_20250503_160206.wav_5,file_name_SERRA_20250503_160206.wav,1
3,chunk_id_SERRA_20250503_220842.wav_0,file_name_SERRA_20250503_220842.wav,1
4,chunk_id_SERRA_20250503_220842.wav_5,file_name_SERRA_20250503_220842.wav,1

In [24]:
from acoustic_knowledge_discovery.features.recommender_prune import recommender_prune

In [25]:
# Build chunk embedding dictionary
emb_column = "sample_models/dim_10_muha.pt_embeddings"
chunk_embs = {
    str(row["chunk_id"]): row[emb_column]
    for row in chunkDS.chunk_ds["train"]
}

pruned_edges = recommender_prune(
    edge_list[["source", "target", "value"]],
    chunk_embeddings=chunk_embs,
    keep_ratio=0.5, 
    gamma=0.6
)

print("original edges:", len(edge_list))
print("pruned edges:", len(pruned_edges))

original edges: 52
pruned edges: 26

In [26]:
import json

with open("acoustic_knowledge_discovery/d3-visualization/graph_representation.json", mode="w") as f:
    json.dump({
        "nodes": list(nodes[["id", "group"]].drop_duplicates().T.to_dict().values()),  
        "links":  list(pruned_edges[["source", "target", "value"]].T.to_dict().values()),
    }, f
)

# Visualization

In [ ]:
!npm install

m#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠼ idealTree: timing idealTree Completed in 35ms[0m
up to date, audited 13 packages in 272ms

found 0 vulnerabilities

1. In terminal, type ` cd acoustic_knowledge_discovery/d3-visualization/ `, assuming that you are in the acoustic_knowledge_discovery parent directory
2. Run ` npx http-server -p 8080 ` in your terminal*
3. Open ` http://127.0.0.1:8080 ` in Safari/Chrome/your choice of browser to interact with the visualization.


*NOTE: If you are getting the error that npx does not exist, then download it here: https://nodejs.org/en/download

The following 3 lines of code open up the visualization in the jupyter notebook, but it currently only works for MacOS users.

In [ ]:
# command = ["npx", "http-server", "-p", "8080"] 
# target_directory = "acoustic_knowledge_discovery/d3-visualization/"

# process = subprocess.Popen(
#     command,
#     cwd=target_directory,
#     #shell=True,
#     preexec_fn=os.setsid  
# )

# # Persist the group leader PID so you can kill it later even after kernel restarts & kill the entire tree
# with open("/tmp/http_server_pid.json", "w") as f:
#     json.dump({"pgid": process.pid}, f)

# print(f"Server started. PGID={process.pid}")

In [ ]:
# #NOTE : You can also open up http://127.0.0.1:8080 in your browser to see it displayed on a larger screen
# HTML(f"""
# <iframe style="background-color: white;" 
#         src="http://127.0.0.1:8080/?nocache={uuid.uuid4()}" 
#         width="1200" height="1000"></iframe>
# """)

In [ ]:
# # Kill the entire process group (gracefully) to stop d3vis port
# with open("/tmp/http_server_pid.json") as f:
#     pgid = json.load(f)["pgid"]


# os.killpg(pgid, signal.SIGTERM)

In [ ]:
#process.kill()